### ISSUE TITLE
Inventories +hp

### ISSUE THREAD

**Issue by QIIxGriimZzQ** [SkyWars/SkyWars#219]
Hi guys! If i have armor like that, befor start game:
![2016-07-02_13 13 35](https://cloud.githubusercontent.com/assets/9472676/16540069/ec1f53d6-4056-11e6-9941-c184eed73930.png)

After game my inventory is empty :( :
`> [13:11:34 ERROR]: [SkyWars] Couldn't broadcast PlayerRespawnAfterGameEnd in SkyWars version skywars-2.1.5 - 2.1.5:
java.lang.IllegalArgumentException: Health must be between 0 and 20.0
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:83) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.daboross.bukkitdev.skywars.game.KillMessages.setHealth(KillMessages.java:6046) ~[SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.player.SavedInventory$1.apply(SavedInventory.java:1104) ~[SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.player.SavedInventory.apply(SavedInventory.java:63) ~[SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.events.listeners.InventorySaveListener.onPlayerRespawn(InventorySaveListener.java:64) ~[SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.events.GameEventDistributor.distribute(GameEventDistributor.java:130) [SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.game.GameHandler.respawnPlayer(GameHandler.java:156) [SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.game.GameHandler.removePlayerFromGame(GameHandler.java:107) [SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.commands.mainsubcommands.LeaveCommand.runCommand$7bc4b72f(LeaveCommand.java:45) [SkyWars.jar:skywars-2.1.5]
at net.daboross.bukkitdev.skywars.libraries.commands.CommandExecutorBase.onCommand(CommandExecutorBase.java:54) [SkyWars.jar:skywars-2.1.5]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) [PerWorldPlugins.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

**Comment by daboross** [comment]
Ok, I think I might have a cause for this, but I can't be sure.

Does this error ever occur without having armor on?

**Comment by daboross** [comment]
I think I have it fixed in the lastest dev build, but I can't be sure. I'm planning on legitimately releasing this version of the plugin as soon as I have access to my main computer which can do a ton more testing on it, but that won't be for ~5-7 days.

For now, if you could try the prerelease v2.1.6-dev-3 and see if that works, that'd be awesome. Here's a link to the download: https://github.com/SkyWars/SkyWars/releases/tag/skywars-2.1.6-dev-3

**Comment by QIIxGriimZzQ** [comment]
I'm so sorry that I didn't write sooner. 
I tried skywars-2.1.6-dev-3
Inventory is OK, but error is still in log

`> [18:02:12 ERROR]: [SkyWars] Couldn't broadcast PlayerRespawnAfterGameEnd in SkyWars version skywars-2.1.6-dev-3 - 2.1.6-SNAPSHOT:
java.lang.IllegalArgumentException: Health must be between 0 and 20.0
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:83) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.daboross.bukkitdev.skywars.util.CrossVersion.setHealth(CrossVersion.java:46) ~[SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.player.SavedInventory$SavedPghData.apply(SavedInventory.java:122) ~[SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.player.SavedInventory$SavedPghData.access$200(SavedInventory.java:74) ~[SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.player.SavedInventory.apply(SavedInventory.java:68) ~[SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.events.listeners.InventorySaveListener.onPlayerRespawn(InventorySaveListener.java:64) ~[SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.events.GameEventDistributor.distribute(GameEventDistributor.java:130) [SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.game.GameHandler.respawnPlayer(GameHandler.java:164) [SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.game.GameHandler.removePlayerFromGame(GameHandler.java:115) [SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.commands.mainsubcommands.LeaveCommand.runCommand(LeaveCommand.java:45) [SkyWars.jar:skywars-2.1.6-dev-3]
at net.daboross.bukkitdev.skywars.libraries.commands.CommandExecutorBase.onCommand(CommandExecutorBase.java:54) [SkyWars.jar:skywars-2.1.6-dev-3]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) [PerWorldPlugins.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

**Comment by QIIxGriimZzQ** [comment]
Now i tried 2.1.7
Log is empty and invnetory OK, but it ruins the armor...
The armor after the game don't adds lives, on the contrary, it hurts the players.

**Comment by QIIxGriimZzQ** [comment]
Now i tried 2.1.6
Same like 2.1.6-dev3
Just fix message error, 2.1.7 ruins the arrmors...

**Comment by daboross** [comment]
Ahh, ok - so I guess there's a problem in how it's storing the data as well. SkyWars close the Bukkit itemstacks to store inventory, so I guess the "armor increasing health" attribute isn't saved in the Bukkit data.

Would it be possible for you to share what you're doing to create this armor, so I can try and reproduce to fix it?

**Comment by QIIxGriimZzQ** [comment]
I have a shop where you can buy command, for example:
`    - give %name% diamond_chestplate 1 0 {AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:16,Operation:0,UUIDLeast:1,UUIDMost:15}],display:{Name:§3[radioactive] §bDiamantové brnění §3[radioactive]}}`

`    - give %name% diamond_chestplate 1 0 {AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:1,UUIDMost:150}],display:{Name:§5[radioactive] §dהניאל's chestplate §5[radioactive]}}`
